Repository hyosung-second-team1/MeeVote, pull requests merged in 2024-05, with the labels that each got.

#3 feat : 개인 일정 삭제 기능 완료
  src/main/java/today/meevote/domain/schedule/controller/ScheduleController.java
  src/main/java/today/meevote/domain/schedule/dao/ScheduleDao.java
  src/main/java/today/meevote/domain/schedule/service/ScheduleService.java
  src/main/java/today/meevote/response/FailureInfo.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/scheduleMapper.xml
Labels: BE

#22 [Feat] 투표 중인 일정 상세조회 API
  src/main/java/today/meevote/domain/auth/dto/request/RegisterDto.java
  src/main/java/today/meevote/domain/member/dto/reponse/GetMyInfoDto.java
  src/main/java/today/meevote/domain/schedule_vote/controller/ScheduleVoteController.java
  src/main/java/today/meevote/domain/schedule_vote/dao/ScheduleVoteDao.java
  src/main/java/today/meevote/domain/schedule_vote/dto/request/CreatePlaceDto.java
  src/main/java/today/meevote/domain/schedule_vote/dto/request/DecidePlaceDto.java
  src/main/java/today/meevote/domain/schedule_vote/dto/response/GetVoteScheduleDetailDto.java
  src/main/java/today/meevote/domain/schedule_vote/dto/response/PlaceToVote.java
  src/main/java/today/meevote/domain/schedule_vote/dto/response/PlaceVotedDto.java
  src/main/java/today/meevote/domain/schedule_vote/dto/response/ScheduleMemberVoteDto.java
  src/main/java/today/meevote/domain/schedule_vote/service/ScheduleVoteService.java
  src/main/java/today/meevote/domain/vote_schedule/controller/VotingScheduleController.java
  src/main/java/today/meevote/domain/vote_schedule/dao/VotingScheduleDao.java
  src/main/java/today/meevote/domain/vote_schedule/dto/request/CreatePlaceDto.java
  src/main/java/today/meevote/domain/vote_schedule/dto/request/DecidePlaceDto.java
  src/main/java/today/meevote/domain/vote_schedule/dto/response/GetVotingScheduleDetailDto.java
  src/main/java/today/meevote/domain/vote_schedule/dto/response/GetVotingScheduleListDto.java
  src/main/java/today/meevote/domain/vote_schedule/dto/response/PlaceToVoteDto.java
  src/main/java/today/meevote/domain/vote_schedule/dto/response/VotingScheduleInfoDto.java
  src/main/java/today/meevote/domain/vote_schedule/dto/response/VotingScheduleMemberDto.java
  src/main/java/today/meevote/domain/vote_schedule/service/VotingScheduleService.java
  src/main/java/today/meevote/response/FailureInfo.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/scheduleVoteMapper.xml
  src/main/resources/mapper/votingScheduleMapper.xml
Labels: BE, 기능

#24 [Feat] 투표받을 장소 추가 API
  src/main/java/today/meevote/domain/member/controller/MemberController.java
  src/main/java/today/meevote/domain/member/dao/MemberDao.java
  src/main/java/today/meevote/domain/member/dto/response/GetMemberForInviteDto.java
  src/main/java/today/meevote/domain/member/dto/response/GetMyInfoDto.java
  src/main/java/today/meevote/domain/member/service/MemberService.java
  src/main/java/today/meevote/domain/vote_schedule/dao/VotingScheduleDao.java
  src/main/java/today/meevote/domain/vote_schedule/dto/request/CreatePlaceDto.java
  src/main/java/today/meevote/domain/voting_schedule/controller/VotingScheduleController.java
  src/main/java/today/meevote/domain/voting_schedule/dao/VotingScheduleDao.java
  src/main/java/today/meevote/domain/voting_schedule/dto/request/CreatePlaceDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/request/DecidePlaceDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/response/GetVotingScheduleDetailDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/response/GetVotingScheduleListDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/response/PlaceToVoteDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/response/VotingScheduleInfoDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/response/VotingScheduleMemberDto.java
  src/main/java/today/meevote/domain/voting_schedule/service/VotingScheduleService.java
  src/main/java/today/meevote/response/FailureInfo.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/memberMapper.xml
  src/main/resources/mapper/votingScheduleMapper.xml
Labels: BE, 기능

#26 [Feat] 모임 일정 생성 api
  src/main/java/today/meevote/domain/schedule/controller/ScheduleController.java
  src/main/java/today/meevote/domain/schedule/dao/ScheduleDao.java
  src/main/java/today/meevote/domain/schedule/dto/request/CreateGroupScheduleDto.java
  src/main/java/today/meevote/domain/schedule/service/ScheduleService.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/java/today/meevote/utils/DateUtil.java
  src/main/resources/mapper/scheduleMapper.xml
Labels: BE, 기능

#28 [feat] : 일정 상세 보기 api
  src/main/java/today/meevote/domain/schedule/controller/ScheduleController.java
  src/main/java/today/meevote/domain/schedule/dao/ScheduleDao.java
  src/main/java/today/meevote/domain/schedule/dto/response/GetScheduleDetailDto.java
  src/main/java/today/meevote/domain/schedule/dto/response/ScheduleDetailInfoDto.java
  src/main/java/today/meevote/domain/schedule/dto/response/ScheduleMemberDto.java
  src/main/java/today/meevote/domain/schedule/service/ScheduleService.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/java/today/meevote/utils/DateUtil.java
  src/main/resources/mapper/scheduleMapper.xml
Labels: BE, 기능

#31 [Feat] 이름으로 회원목록 검색 API
  src/main/java/today/meevote/domain/member/controller/MemberController.java
  src/main/java/today/meevote/domain/member/dao/MemberDao.java
  src/main/java/today/meevote/domain/member/dto/response/GetMemberForInviteDto.java
  src/main/java/today/meevote/domain/member/service/MemberService.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/memberMapper.xml
Labels: BE, 기능

#32 [Feat] 장소 투표하기 API
  src/main/java/today/meevote/domain/voting_schedule/controller/VotingScheduleController.java
  src/main/java/today/meevote/domain/voting_schedule/dao/VotingScheduleDao.java
  src/main/java/today/meevote/domain/voting_schedule/dto/request/SelectPlaceDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/response/GetVotingScheduleDetailDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/response/PlaceToVoteDto.java
  src/main/java/today/meevote/domain/voting_schedule/dto/response/VotingScheduleInfoDto.java
  src/main/java/today/meevote/domain/voting_schedule/service/VotingScheduleService.java
  src/main/java/today/meevote/response/FailureInfo.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/votingScheduleMapper.xml
Labels: BE, 기능

#35 feat : 예정 중인 일정목록 조회 api
  src/main/java/today/meevote/domain/schedule/controller/ScheduleController.java
  src/main/java/today/meevote/domain/schedule/dao/ScheduleDao.java
  src/main/java/today/meevote/domain/schedule/service/ScheduleService.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/scheduleMapper.xml
Labels: BE, 기능

#40 [ Feat ] 모임일정 나가기 api
  src/main/java/today/meevote/domain/schedule/controller/ScheduleController.java
  src/main/java/today/meevote/domain/schedule/dao/ScheduleDao.java
  src/main/java/today/meevote/domain/schedule/service/ScheduleService.java
  src/main/java/today/meevote/response/FailureInfo.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/scheduleMapper.xml
Labels: BE, 기능

#43 [Feat] 장소 확정하기 API
  src/main/java/today/meevote/domain/voting_schedule/controller/VotingScheduleController.java
  src/main/java/today/meevote/domain/voting_schedule/dao/VotingScheduleDao.java
  src/main/java/today/meevote/domain/voting_schedule/service/VotingScheduleService.java
  src/main/java/today/meevote/response/FailureInfo.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/votingScheduleMapper.xml
Labels: BE, 기능

#44 [ Feat ] 지난 일정 목록 조회 api
  src/main/java/today/meevote/domain/schedule/controller/ScheduleController.java
  src/main/java/today/meevote/domain/schedule/dao/ScheduleDao.java
  src/main/java/today/meevote/domain/schedule/dto/request/CreateGroupScheduleDto.java
  src/main/java/today/meevote/domain/schedule/dto/response/GetScheduleListDto.java
  src/main/java/today/meevote/domain/schedule/service/ScheduleService.java
  src/main/resources/mapper/scheduleMapper.xml
Labels: BE, 기능

#49 [Feat] 알림 조회 및 읽기 처리 API
  src/main/java/today/meevote/domain/notify/controller/NotifyController.java
  src/main/java/today/meevote/domain/notify/dao/NotifyDao.java
  src/main/java/today/meevote/domain/notify/dto/GetNotifyListDto.java
  src/main/java/today/meevote/domain/notify/service/NotifyService.java
  src/main/java/today/meevote/response/FailureInfo.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/notifyMapper.xml
  src/main/resources/sql/sql_0511
  src/main/resources/sql/sql_0513
Labels: BE, 기능

#59 [ Fix ] : 예정 목록 조회 쿼리문 에러 수정
  src/main/resources/mapper/scheduleMapper.xml
Labels: 버그, BE, 수정

#61 [Feat]: 알림 조회 API
  src/main/java/today/meevote/domain/notify/dto/GetNotifyListDto.java
  src/main/resources/mapper/notifyMapper.xml
  src/main/resources/sql/sql_0513
Labels: BE, 기능

#62 [Feat] : 지난 일정 조회 기능 수정
  src/main/java/today/meevote/domain/schedule/controller/ScheduleController.java
  src/main/java/today/meevote/domain/voting_schedule/dao/VotingScheduleDao.java
Labels: 버그, BE, 수정

#64 [Feat] 초대, 확정 API 호출 시 알림 생성
  src/main/java/today/meevote/domain/notify/controller/NotifyController.java
  src/main/java/today/meevote/domain/notify/dao/NotifyDao.java
  src/main/java/today/meevote/domain/notify/service/NotifyService.java
  src/main/java/today/meevote/domain/schedule/dao/ScheduleDao.java
  src/main/java/today/meevote/domain/schedule/service/ScheduleService.java
  src/main/java/today/meevote/domain/voting_schedule/service/VotingScheduleService.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/notifyMapper.xml
  src/main/resources/mapper/scheduleMapper.xml
Labels: BE, 기능

#72 [Feat] 내 일정 통계 API
  src/main/java/today/meevote/domain/statistics/controller/StatsController.java
  src/main/java/today/meevote/domain/statistics/dao/StatsDao.java
  src/main/java/today/meevote/domain/statistics/dto/response/GetMyCategoryStatsDto.java
  src/main/java/today/meevote/domain/statistics/dto/response/GetMyScheduleStatsDto.java
  src/main/java/today/meevote/domain/statistics/service/StatsService.java
  src/main/java/today/meevote/response/SuccessInfo.java
  src/main/resources/mapper/statsMapper.xml
Labels: BE, 기능

#73 [Feat] : 날짜 유효성 검사 추가
  src/main/java/today/meevote/domain/schedule/dao/ScheduleDao.java
  src/main/java/today/meevote/domain/schedule/service/ScheduleService.java
  src/main/java/today/meevote/utils/DateUtil.java
  src/main/resources/mapper/scheduleMapper.xml
Labels: 버그, BE, 수정

#76 [Chore] 환경 변수 수정
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/today/meevote/MeevoteApplicationTests.java
Labels: 인프라

#77 [Infra] 자동 배포
  .github/workflows/deploy.yml
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/today/meevote/MeevoteApplicationTests.java
Labels: 인프라

#82 [Refactor] 동시성 처리
  src/main/java/today/meevote/domain/voting_schedule/service/VotingScheduleService.java
  src/main/java/today/meevote/response/FailureInfo.java
  src/main/resources/mapper/notifyMapper.xml
  src/main/resources/sql/sql_0515
Labels: 리팩토링, BE, 수정
